PaperTrail.Web/Controllers/BranchController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PaperTrail.Data.Interfaces;
using PaperTrail.Web.Models.Branch;

namespace PaperTrail.Web.Controllers
{
    public class BranchController : Controller
    {
        private IBranchOffice _branch;

        public BranchController(IBranchOffice branch)
        {
            _branch = branch;
        }
        public IActionResult Index()
        {
            var branches = _branch.GetAll().Select(branch => new BranchDetailModel
            {
                Id = branch.Id,
                Name = branch.Name,
                IsOpen = _branch.IsBranchOpen(branch.Id),
                NumberOfAssets = _branch.GetAssets(branch.Id).Count(),
                NumberOfPatrons = _branch.GetPatrons(branch.Id).Count(),

            });

            var model = new BranchIndexModel()
            {
                Branches = branches
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var branch = _branch.Get(id);

            var model = new BranchDetailModel
            {
                Id = branch.Id,
                Name = branch.Name,
                Address = branch.Address,
                Description = branch.Description,
                Telephone = branch.Telephone,
                IsOpen = _branch.IsBranchOpen(id),
                OpenDate = branch.OpenDate.ToString("yyyy-MM-dd"),
                NumberOfAssets = _branch.GetAssets(id).Count(),
                NumberOfPatrons = _branch.GetPatrons(id).Count(),
                TotalAssetValue = _branch.GetAssets(id).Sum(a => a.Cost),
                ImageUrl = branch.ImageUrl,
                HoursOpen = _branch.GetBranchHours(id),
            };

            return View(model);
        }
    }
}

PaperTrail.Web/Controllers/CatalogController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PaperTrail.Data.Interfaces;
using PaperTrail.Web.Models.Catalog;
using PaperTrail.Web.Models.CheckoutModels;

namespace PaperTrail.Web.Controllers
{
    public class CatalogController : Controller
    {
        private IBranchAsset _context;
        private ICheckout _checkout;

        public CatalogController(IBranchAsset context, ICheckout checkout)
        {
            _context = context;
            _checkout = checkout;
        }

        public IActionResult Index()
        {
            var contextModels = _context.GetAll();
            var listingResult = contextModels.Select(result => new CatalogIndexListings
            {
                Id = result.Id,
                ImageUrl = result.ImageUrl,
                AuthorOrDirector = _context.GetAuthorOrDirector(result.Id),
                DeweyCallNumber = _context.GetDeweyIndex(result.Id),
                Title = result.Title,
                Type = _context.GetType(result.Id)
            });

            var model = new CatalogIndex()
            {
                Indexes = listingResult
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var context = _context.GetById(id);

            var currentReservations = _checkout.GetCurrentReservations(id)
                .Select(res => new CatalogIndexReservation
                {
                    ReservationPlaced = _checkout.GetCurrentReservationPlaced(res.Id),
                    PatronName = _checkout.GetCurrentReservationPatronName(res.Id)
                });

            var model = new CatalogIndexDetail
            {
                IndexId = id,
                Title = context.Title,
                Year = context.Year,
                Cost = context.Cost,
                Status = context.Status.Name,
                ImageUrl = context.ImageUrl,
                AuthorOrDirector = _context.GetAuthorOrDirector(id),
                CurrentLocation = _context.GetCurrentLocation(id).Name,
                DeweyCallNumber = _context.GetDeweyIndex(id),
                ISBN = _context.GetIsbn(id),
                LatestCheckout = _checkout.GetLatestCheckout(id),
                PatronName = _checkout.GetCurrentCheckoutPatron(id),
                CurrentReservations = currentReservations,
                CheckoutHistory = _checkout.GetCheckoutHistory(id)
            };

            return View(model);
        }

        public IActionResult Checkout(int id)
        {
            var item = _context.GetById(id);

            var model = new CheckoutModel
            {
                ItemId = id,
                ImageUrl = item.ImageUrl,
                Title = item.Title,
                PatronCardId = "",
                IsCheckedOut = _checkout.IsCheckedOut(id)
            };
            return View(model);
        }

        public IActionResult ReturnCheckoutItem(int id)
        {
            _checkout.ReturnItem(id);
            return RedirectToAction("Detail", new { id = id });

        }
        
        public IActionResult Reserve(int id)
        {
            var item = _context.GetById(id);

            var model = new CheckoutModel
            {
                ItemId = id,
                ImageUrl = item.ImageUrl,
                Title = item.Title,
                PatronCardId = "",
                IsCheckedOut = _checkout.IsCheckedOut(id),
                ReservationCount = _checkout.GetCurrentReservations(id).Count()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult PlaceCheckout(int itemId, int patronCardId)
        {
            _checkout.CheckoutItem(itemId, patronCardId);
            return RedirectToAction("Detail", new { id = itemId });
        }

        [HttpPost]
        public IActionResult PlaceReservation(int itemId, int patronCardId)
        {
            _checkout.PlaceReservation(itemId, patronCardId);
            return RedirectToAction("Detail", new { id = itemId });
        }

        public IActionResult MarkUnavailable(int itemId)
        {
            _checkout.MarkUnavailable(itemId);
            return RedirectToAction("Detail", new { id = itemId });
        }
        
        public IActionResult MarkAvailable(int itemId)
        {
            _checkout.MarkAvailable(itemId);
            return RedirectToAction("Detail", new { id = itemId });
        }
    }
}

PaperTrail.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PaperTrail.Web.Models;

namespace PaperTrail.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PaperTrail.Web/Controllers/PatronController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PaperTrail.Data.Interfaces;
using PaperTrail.Data.Models;
using PaperTrail.Web.Models.Patron;

namespace PaperTrail.Web.Controllers
{
    public class PatronController : Controller
    {
        private IPatron _patron;
        public PatronController(IPatron patron)
        {
            _patron = patron;
        }

        public IActionResult Index()
        {
            var allPatrons = _patron.GetAll();

            var patronModels = allPatrons.Select(x => new PatronDetailModel
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                PatronCardId = x.PatronCard.Id,
                OverdueFees = x.PatronCard.Fees,
                LocalBranchOffice = x.LocalBranchOffice.Name
            }).ToList();

            var model = new PatronIndexModel()
            {
                Patrons = patronModels
            };

            return View(model);
        }


        public IActionResult Detail(int patronId){
            var x = _patron.Get(patronId);

            var model = new PatronDetailModel{
                FirstName = x.FirstName,
                LastName = x.LastName,
                MemberSince = x.PatronCard.Created,
                Phone = x.PhoneNumber,
                PatronCardId = x.PatronCard.Id,
                OverdueFees = x.PatronCard.Fees,
                LocalBranchOffice = x.LocalBranchOffice.Name,
                ItemCheckedOut = _patron
                    .GetPatronCheckouts(patronId)
                    .ToList() ?? new System.Collections.Generic.List<Checkout>(),
                CheckoutHistory = _patron.GetCheckoutHistory(patronId),
                Holds = _patron.GetHolds(patronId)
            };

            return View(model);
        }

    }
}

PaperTrail.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="text-center">
            <h3 class="display-5">Welcome</h3>
        </div>
    </div>
</section>

<section class="content">
        <div class="row justify-content-center">
            <div class="d-flex flex-wrap" style="margin-bottom: 8rem;">
                <!-- Catalog Card -->
                <div class="col-sm-4">
                    <div class="card" style="padding: 5px;">
                        <img src="/images/catalog_card.jpg" alt="catalog img" class="card-img">
                        <div class="card-img-overlay card__overlay-text">
                            <h3 class="card-title">
                                <a asp-controller="Catalog" asp-action="Index" role="button" class="btn btn-block btn-primary">Catalog</a>
                            </h3>
                        </div>
                    </div>
                </div>
                <!-- ./Catalog End -->

                <!-- Patrons Card -->
                <div class="col-sm-4">
                    <div class="card" style="padding: 5px;">
                        <img src="/images/patrons_card.jpg" alt="patron img" class="card-img">
                        <div class="card-img-overlay card__overlay-text">
                            <h3 class="card-title">
                                <a asp-controller="Patron" asp-action="Index" role="button" class="btn btn-block btn-primary">Patrons</a>
                            </h3>
                        </div>
                    </div>
                </div>
                <!-- ./Patrons Card  -->

                <!-- Branches Card -->
                <div class="col-sm-4">
                    <div class="card" style="padding: 5px;">
                        <img src="/images/branches_card.jpg" alt="branch img" class="card-img">
                        <div class="card-img-overlay card__overlay-text">
                            <h3 class="card-title text-center">
                            <a asp-controller="Branch" asp-action="Index" role="button" class="btn btn-block btn-primary">Branches</a>
                            </h3>
                        </div>
                    </div>
                </div>
                <!-- ./Branches End -->
            </div>
        </div>
        <!-- ./Row -->
</section>

<style>
    .card__overlay-text{
        display: flex;
        align-items: flex-end !important;
        justify-content: center;
    }
</style>